In [2]:
import numpy as np

In [7]:
import numpy as np
from pysindy.differentiation import FiniteDifference

# Example usage
t = np.linspace(0, 1, 5)
X = np.vstack((np.sin(t), np.cos(t))).T
fd = FiniteDifference(order=3,d=2)

# Coefficients for interior points
coeffs_interior = fd._constant_coefficients(t[1] - t[0])

# Coefficients for boundary points with forward differences
coeffs_boundary_forward = fd._coefficients_boundary_forward(t)

# Coefficients for boundary points with periodic differences
coeffs_boundary_periodic = fd._coefficients_boundary_periodic(t)

# Print or use the coefficients as needed
print("Coefficients for interior points:", coeffs_interior)
print("Coefficients for boundary points with forward differences:", coeffs_boundary_forward)

Coefficients for interior points: [ 16. -32.  16.   0.]
Coefficients for boundary points with forward differences: [[  46.66666667 -138.66666667  152.          -74.66666667   14.66666667]
 [  14.66666667  -26.66666667    8.            5.33333333   -1.33333333]
 [  46.66666667 -138.66666667  152.          -74.66666667   14.66666667]]
Coefficients for boundary points with periodic differences: [[ 16. -32.  16.   0.]
 [ 16. -32.  16.  -0.]]


In [21]:
n=20
j=n/2
for l in range(n+1):
    sum=0.0
    if l!=j:
        prod=1.0
        for k in range(n+1):
            if k!=j and k!=l:
                prod=prod*(j-k)
        sum=sum+prod
print(sum)

-1316818944000.0


In [ ]:
# import library
import sympy as sp

# define symbolic variable
t = sp.symbols('x')

# define symbolic equation
eq = sp.exp(t / 2) * (sp.sin(t / 3) ** 2)

# find fourth order derivative
fourth_order_derivative = eq.diff(t, t, t, t)